@echo off
set MATLAB=C:\Program Files\MATLAB\R2014b
"C:\PROGRA~1\MATLAB\R2014b\bin\win64\gmake" -f helicecontrolV2.mk  EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 TMW_EXTMODE_TESTING=0 OPTS="-DON_TARGET_WAIT_FOR_START=1"
